%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1024
image_height: 768
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 886.8100
   fy: 886.8100
   cx: 512
   cy: 384
